<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;

final class CurrencyController extends AbstractController
{
    #[Route('/', name: 'currency_index', methods: ['GET'])]
    public function index(Request $request, HttpClientInterface $client): Response
    {
        $amount = (float) $request->query->get('amount', 1);
        $from   = $request->query->get('from', 'EUR');
        $to     = $request->query->get('to', 'TND');

        $rate = null;
        $result = null;

        $apiKey = $_ENV['EXCHANGE_API_KEY'] ?? null;

        $symbols = [
            'AED' => ['description' => 'United Arab Emirates Dirham', 'flag' => '🇦🇪', 'flag_url' => 'https://flagcdn.com/ae.svg'],
            'AFN' => ['description' => 'Afghan Afghani', 'flag' => '🇦🇫', 'flag_url' => 'https://flagcdn.com/af.svg'],
            'ALL' => ['description' => 'Albanian Lek', 'flag' => '🇦🇱', 'flag_url' => 'https://flagcdn.com/al.svg'],
            'AMD' => ['description' => 'Armenian Dram', 'flag' => '🇦🇲', 'flag_url' => 'https://flagcdn.com/am.svg'],
            'ANG' => ['description' => 'Netherlands Antillean Guilder', 'flag' => '🇧🇶', 'flag_url' => 'https://flagcdn.com/bq.svg'],
            'AOA' => ['description' => 'Angolan Kwanza', 'flag' => '🇦🇴', 'flag_url' => 'https://flagcdn.com/ao.svg'],
            'ARS' => ['description' => 'Argentine Peso', 'flag' => '🇦🇷', 'flag_url' => 'https://flagcdn.com/ar.svg'],
            'AUD' => ['description' => 'Australian Dollar', 'flag' => '🇦🇺', 'flag_url' => 'https://flagcdn.com/au.svg'],
            'AWG' => ['description' => 'Aruban Florin', 'flag' => '🇦🇼', 'flag_url' => 'https://flagcdn.com/aw.svg'],
            'AZN' => ['description' => 'Azerbaijani Manat', 'flag' => '🇦🇿', 'flag_url' => 'https://flagcdn.com/az.svg'],
            'BAM' => ['description' => 'Bosnia-Herzegovina Convertible Mark', 'flag' => '🇧🇦', 'flag_url' => 'https://flagcdn.com/ba.svg'],
            'BBD' => ['description' => 'Barbadian Dollar', 'flag' => '🇧🇧', 'flag_url' => 'https://flagcdn.com/bb.svg'],
            'BDT' => ['description' => 'Bangladeshi Taka', 'flag' => '🇧🇩', 'flag_url' => 'https://flagcdn.com/bd.svg'],
            'BGN' => ['description' => 'Bulgarian Lev', 'flag' => '🇧🇬', 'flag_url' => 'https://flagcdn.com/bg.svg'],
            'BHD' => ['description' => 'Bahraini Dinar', 'flag' => '🇧🇭', 'flag_url' => 'https://flagcdn.com/bh.svg'],
            'BIF' => ['description' => 'Burundian Franc', 'flag' => '🇧🇮', 'flag_url' => 'https://flagcdn.com/bi.svg'],
            'BMD' => ['description' => 'Bermudian Dollar', 'flag' => '🇧🇲', 'flag_url' => 'https://flagcdn.com/bm.svg'],
            'BND' => ['description' => 'Brunei Dollar', 'flag' => '🇧🇳', 'flag_url' => 'https://flagcdn.com/bn.svg'],
            'BOB' => ['description' => 'Bolivian Boliviano', 'flag' => '🇧🇴', 'flag_url' => 'https://flagcdn.com/bo.svg'],
            'BRL' => ['description' => 'Brazilian Real', 'flag' => '🇧🇷', 'flag_url' => 'https://flagcdn.com/br.svg'],
            'BSD' => ['description' => 'Bahamian Dollar', 'flag' => '🇧🇸', 'flag_url' => 'https://flagcdn.com/bs.svg'],
            'BTN' => ['description' => 'Bhutanese Ngultrum', 'flag' => '🇧🇹', 'flag_url' => 'https://flagcdn.com/bt.svg'],
            'BWP' => ['description' => 'Botswana Pula', 'flag' => '🇧🇼', 'flag_url' => 'https://flagcdn.com/bw.svg'],
            'BYN' => ['description' => 'Belarusian Ruble', 'flag' => '🇧🇾', 'flag_url' => 'https://flagcdn.com/by.svg'],
            'BZD' => ['description' => 'Belize Dollar', 'flag' => '🇧🇿', 'flag_url' => 'https://flagcdn.com/bz.svg'],
            'CAD' => ['description' => 'Canadian Dollar', 'flag' => '🇨🇦', 'flag_url' => 'https://flagcdn.com/ca.svg'],
            'CDF' => ['description' => 'Congolese Franc', 'flag' => '🇨🇩', 'flag_url' => 'https://flagcdn.com/cd.svg'],
            'CHF' => ['description' => 'Swiss Franc', 'flag' => '🇨🇭', 'flag_url' => 'https://flagcdn.com/ch.svg'],
            'CLP' => ['description' => 'Chilean Peso', 'flag' => '🇨🇱', 'flag_url' => 'https://flagcdn.com/cl.svg'],
            'CNY' => ['description' => 'Chinese Yuan', 'flag' => '🇨🇳', 'flag_url' => 'https://flagcdn.com/cn.svg'],
            'COP' => ['description' => 'Colombian Peso', 'flag' => '🇨🇴', 'flag_url' => 'https://flagcdn.com/co.svg'],
            'CRC' => ['description' => 'Costa Rican Colón', 'flag' => '🇨🇷', 'flag_url' => 'https://flagcdn.com/cr.svg'],
            'CUC' => ['description' => 'Cuban Convertible Peso', 'flag' => '🇨🇺', 'flag_url' => 'https://flagcdn.com/cu.svg'],
            'CUP' => ['description' => 'Cuban Peso', 'flag' => '🇨🇺', 'flag_url' => 'https://flagcdn.com/cu.svg'],
            'CVE' => ['description' => 'Cape Verdean Escudo', 'flag' => '🇨🇻', 'flag_url' => 'https://flagcdn.com/cv.svg'],
            'CZK' => ['description' => 'Czech Koruna', 'flag' => '🇨🇿', 'flag_url' => 'https://flagcdn.com/cz.svg'],
            'DJF' => ['description' => 'Djiboutian Franc', 'flag' => '🇩🇯', 'flag_url' => 'https://flagcdn.com/dj.svg'],
            'DKK' => ['description' => 'Danish Krone', 'flag' => '🇩🇰', 'flag_url' => 'https://flagcdn.com/dk.svg'],
            'DOP' => ['description' => 'Dominican Peso', 'flag' => '🇩🇴', 'flag_url' => 'https://flagcdn.com/do.svg'],
            'DZD' => ['description' => 'Algerian Dinar', 'flag' => '🇩🇿', 'flag_url' => 'https://flagcdn.com/dz.svg'],
            'EGP' => ['description' => 'Egyptian Pound', 'flag' => '🇪🇬', 'flag_url' => 'https://flagcdn.com/eg.svg'],
            'ERN' => ['description' => 'Eritrean Nakfa', 'flag' => '🇪🇷', 'flag_url' => 'https://flagcdn.com/er.svg'],
            'ETB' => ['description' => 'Ethiopian Birr', 'flag' => '🇪🇹', 'flag_url' => 'https://flagcdn.com/et.svg'],
            'EUR' => ['description' => 'Euro', 'flag' => '🇪🇺', 'flag_url' => 'https://flagcdn.com/eu.svg'],
            'FJD' => ['description' => 'Fijian Dollar', 'flag' => '🇫🇯', 'flag_url' => 'https://flagcdn.com/fj.svg'],
            'FKP' => ['description' => 'Falkland Islands Pound', 'flag' => '🇫🇰', 'flag_url' => 'https://flagcdn.com/fk.svg'],
            'GBP' => ['description' => 'British Pound Sterling', 'flag' => '🇬🇧', 'flag_url' => 'https://flagcdn.com/gb.svg'],
            'GEL' => ['description' => 'Georgian Lari', 'flag' => '🇬🇪', 'flag_url' => 'https://flagcdn.com/ge.svg'],
            'GHS' => ['description' => 'Ghanaian Cedi', 'flag' => '🇬🇭', 'flag_url' => 'https://flagcdn.com/gh.svg'],
            'GIP' => ['description' => 'Gibraltar Pound', 'flag' => '🇬🇮', 'flag_url' => 'https://flagcdn.com/gi.svg'],
            'GMD' => ['description' => 'Gambian Dalasi', 'flag' => '🇬🇲', 'flag_url' => 'https://flagcdn.com/gm.svg'],
            'GNF' => ['description' => 'Guinean Franc', 'flag' => '🇬🇳', 'flag_url' => 'https://flagcdn.com/gn.svg'],
            'GTQ' => ['description' => 'Guatemalan Quetzal', 'flag' => '🇬🇹', 'flag_url' => 'https://flagcdn.com/gt.svg'],
            'GYD' => ['description' => 'Guyanese Dollar', 'flag' => '🇬🇾', 'flag_url' => 'https://flagcdn.com/gy.svg'],
            'HKD' => ['description' => 'Hong Kong Dollar', 'flag' => '🇭🇰', 'flag_url' => 'https://flagcdn.com/hk.svg'],
            'HNL' => ['description' => 'Honduran Lempira', 'flag' => '🇭🇳', 'flag_url' => 'https://flagcdn.com/hn.svg'],
            'HRK' => ['description' => 'Croatian Kuna', 'flag' => '🇭🇷', 'flag_url' => 'https://flagcdn.com/hr.svg'],
            'HTG' => ['description' => 'Haitian Gourde', 'flag' => '🇭🇹', 'flag_url' => 'https://flagcdn.com/ht.svg'],
            'HUF' => ['description' => 'Hungarian Forint', 'flag' => '🇭🇺', 'flag_url' => 'https://flagcdn.com/hu.svg'],
            'IDR' => ['description' => 'Indonesian Rupiah', 'flag' => '🇮🇩', 'flag_url' => 'https://flagcdn.com/id.svg'],
            'ILS' => ['description' => 'Israeli New Shekel', 'flag' => '🇮🇱', 'flag_url' => 'https://flagcdn.com/il.svg'],
            'INR' => ['description' => 'Indian Rupee', 'flag' => '🇮🇳', 'flag_url' => 'https://flagcdn.com/in.svg'],
            'IQD' => ['description' => 'Iraqi Dinar', 'flag' => '🇮🇶', 'flag_url' => 'https://flagcdn.com/iq.svg'],
            'IRR' => ['description' => 'Iranian Rial', 'flag' => '🇮🇷', 'flag_url' => 'https://flagcdn.com/ir.svg'],
            'ISK' => ['description' => 'Icelandic Króna', 'flag' => '🇮🇸', 'flag_url' => 'https://flagcdn.com/is.svg'],
            'JMD' => ['description' => 'Jamaican Dollar', 'flag' => '🇯🇲', 'flag_url' => 'https://flagcdn.com/jm.svg'],
            'JOD' => ['description' => 'Jordanian Dinar', 'flag' => '🇯🇴', 'flag_url' => 'https://flagcdn.com/jo.svg'],
            'JPY' => ['description' => 'Japanese Yen', 'flag' => '🇯🇵', 'flag_url' => 'https://flagcdn.com/jp.svg'],
            'KES' => ['description' => 'Kenyan Shilling', 'flag' => '🇰🇪', 'flag_url' => 'https://flagcdn.com/ke.svg'],
            'KGS' => ['description' => 'Kyrgyzstani Som', 'flag' => '🇰🇬', 'flag_url' => 'https://flagcdn.com/kg.svg'],
            'KHR' => ['description' => 'Cambodian Riel', 'flag' => '🇰🇭', 'flag_url' => 'https://flagcdn.com/kh.svg'],
            'KMF' => ['description' => 'Comorian Franc', 'flag' => '🇰🇲', 'flag_url' => 'https://flagcdn.com/km.svg'],
            'KPW' => ['description' => 'North Korean Won', 'flag' => '🇰🇵', 'flag_url' => 'https://flagcdn.com/kp.svg'],
            'KRW' => ['description' => 'South Korean Won', 'flag' => '🇰🇷', 'flag_url' => 'https://flagcdn.com/kr.svg'],
            'KWD' => ['description' => 'Kuwaiti Dinar', 'flag' => '🇰🇼', 'flag_url' => 'https://flagcdn.com/kw.svg'],
            'KYD' => ['description' => 'Cayman Islands Dollar', 'flag' => '🇰🇾', 'flag_url' => 'https://flagcdn.com/ky.svg'],
            'KZT' => ['description' => 'Kazakhstani Tenge', 'flag' => '🇰🇿', 'flag_url' => 'https://flagcdn.com/kz.svg'],
            'LAK' => ['description' => 'Lao Kip', 'flag' => '🇱🇦', 'flag_url' => 'https://flagcdn.com/la.svg'],
            'LBP' => ['description' => 'Lebanese Pound', 'flag' => '🇱🇧', 'flag_url' => 'https://flagcdn.com/lb.svg'],
            'LKR' => ['description' => 'Sri Lankan Rupee', 'flag' => '🇱🇰', 'flag_url' => 'https://flagcdn.com/lk.svg'],
            'LRD' => ['description' => 'Liberian Dollar', 'flag' => '🇱🇷', 'flag_url' => 'https://flagcdn.com/lr.svg'],
            'LSL' => ['description' => 'Lesotho Loti', 'flag' => '🇱🇸', 'flag_url' => 'https://flagcdn.com/ls.svg'],
            'LYD' => ['description' => 'Libyan Dinar', 'flag' => '🇱🇾', 'flag_url' => 'https://flagcdn.com/ly.svg'],
            'MAD' => ['description' => 'Moroccan Dirham', 'flag' => '🇲🇦', 'flag_url' => 'https://flagcdn.com/ma.svg'],
            'MDL' => ['description' => 'Moldovan Leu', 'flag' => '🇲🇩', 'flag_url' => 'https://flagcdn.com/md.svg'],
            'MGA' => ['description' => 'Malagasy Ariary', 'flag' => '🇲🇬', 'flag_url' => 'https://flagcdn.com/mg.svg'],
            'MKD' => ['description' => 'Macedonian Denar', 'flag' => '🇲🇰', 'flag_url' => 'https://flagcdn.com/mk.svg'],
            'MMK' => ['description' => 'Myanma Kyat', 'flag' => '🇲🇲', 'flag_url' => 'https://flagcdn.com/mm.svg'],
            'MNT' => ['description' => 'Mongolian Tögrög', 'flag' => '🇲🇳', 'flag_url' => 'https://flagcdn.com/mn.svg'],
            'MOP' => ['description' => 'Macanese Pataca', 'flag' => '🇲🇴', 'flag_url' => 'https://flagcdn.com/mo.svg'],
            'MRU' => ['description' => 'Mauritanian Ouguiya', 'flag' => '🇲🇷', 'flag_url' => 'https://flagcdn.com/mr.svg'],
            'MUR' => ['description' => 'Mauritian Rupee', 'flag' => '🇲🇺', 'flag_url' => 'https://flagcdn.com/mu.svg'],
            'MVR' => ['description' => 'Maldivian Rufiyaa', 'flag' => '🇲🇻', 'flag_url' => 'https://flagcdn.com/mv.svg'],
            'MWK' => ['description' => 'Malawian Kwacha', 'flag' => '🇲🇼', 'flag_url' => 'https://flagcdn.com/mw.svg'],
            'MXN' => ['description' => 'Mexican Peso', 'flag' => '🇲🇽', 'flag_url' => 'https://flagcdn.com/mx.svg'],
            'MYR' => ['description' => 'Malaysian Ringgit', 'flag' => '🇲🇾', 'flag_url' => 'https://flagcdn.com/my.svg'],
            'MZN' => ['description' => 'Mozambican Metical', 'flag' => '🇲🇿', 'flag_url' => 'https://flagcdn.com/mz.svg'],
            'NAD' => ['description' => 'Namibian Dollar', 'flag' => '🇳🇦', 'flag_url' => 'https://flagcdn.com/na.svg'],
            'NGN' => ['description' => 'Nigerian Naira', 'flag' => '🇳🇬', 'flag_url' => 'https://flagcdn.com/ng.svg'],
            'NIO' => ['description' => 'Nicaraguan Córdoba', 'flag' => '🇳🇮', 'flag_url' => 'https://flagcdn.com/ni.svg'],
            'NOK' => ['description' => 'Norwegian Krone', 'flag' => '🇳🇴', 'flag_url' => 'https://flagcdn.com/no.svg'],
            'NPR' => ['description' => 'Nepalese Rupee', 'flag' => '🇳🇵', 'flag_url' => 'https://flagcdn.com/np.svg'],
            'NZD' => ['description' => 'New Zealand Dollar', 'flag' => '🇳🇿', 'flag_url' => 'https://flagcdn.com/nz.svg'],
            'OMR' => ['description' => 'Omani Rial', 'flag' => '🇴🇲', 'flag_url' => 'https://flagcdn.com/om.svg'],
            'PAB' => ['description' => 'Panamanian Balboa', 'flag' => '🇵🇦', 'flag_url' => 'https://flagcdn.com/pa.svg'],
            'PEN' => ['description' => 'Peruvian Nuevo Sol', 'flag' => '🇵🇪', 'flag_url' => 'https://flagcdn.com/pe.svg'],
            'PGK' => ['description' => 'Papua New Guinean Kina', 'flag' => '🇵🇬', 'flag_url' => 'https://flagcdn.com/pg.svg'],
            'PHP' => ['description' => 'Philippine Peso', 'flag' => '🇵🇭', 'flag_url' => 'https://flagcdn.com/ph.svg'],
            'PKR' => ['description' => 'Pakistani Rupee', 'flag' => '🇵🇰', 'flag_url' => 'https://flagcdn.com/pk.svg'],
            'PLN' => ['description' => 'Polish Złoty', 'flag' => '🇵🇱', 'flag_url' => 'https://flagcdn.com/pl.svg'],
            'PYG' => ['description' => 'Paraguayan Guaraní', 'flag' => '🇵🇾', 'flag_url' => 'https://flagcdn.com/py.svg'],
            'QAR' => ['description' => 'Qatari Riyal', 'flag' => '🇶🇦', 'flag_url' => 'https://flagcdn.com/qa.svg'],
            'RON' => ['description' => 'Romanian Leu', 'flag' => '🇷🇴', 'flag_url' => 'https://flagcdn.com/ro.svg'],
            'RSD' => ['description' => 'Serbian Dinar', 'flag' => '🇷🇸', 'flag_url' => 'https://flagcdn.com/rs.svg'],
            'RUB' => ['description' => 'Russian Ruble', 'flag' => '🇷🇺', 'flag_url' => 'https://flagcdn.com/ru.svg'],
            'SAR' => ['description' => 'Saudi Riyal', 'flag' => '🇸🇦', 'flag_url' => 'https://flagcdn.com/sa.svg'],
            'SBD' => ['description' => 'Solomon Islands Dollar', 'flag' => '🇸🇧', 'flag_url' => 'https://flagcdn.com/sb.svg'],
            'SCR' => ['description' => 'Seychellois Rupee', 'flag' => '🇸🇨', 'flag_url' => 'https://flagcdn.com/sc.svg'],
            'SDG' => ['description' => 'Sudanese Pound', 'flag' => '🇸🇩', 'flag_url' => 'https://flagcdn.com/sd.svg'],
            'SEK' => ['description' => 'Swedish Krona', 'flag' => '🇸🇪', 'flag_url' => 'https://flagcdn.com/se.svg'],
            'SGD' => ['description' => 'Singapore Dollar', 'flag' => '🇸🇬', 'flag_url' => 'https://flagcdn.com/sg.svg'],
            'SHP' => ['description' => 'Saint Helena Pound', 'flag' => '🇸🇭', 'flag_url' => 'https://flagcdn.com/sh.svg'],
            'SLL' => ['description' => 'Sierra Leonean Leone', 'flag' => '🇸🇱', 'flag_url' => 'https://flagcdn.com/sl.svg'],
            'SOS' => ['description' => 'Somali Shilling', 'flag' => '🇸🇴', 'flag_url' => 'https://flagcdn.com/so.svg'],
            'SRD' => ['description' => 'Surinamese Dollar', 'flag' => '🇸🇷', 'flag_url' => 'https://flagcdn.com/sr.svg'],
            'STN' => ['description' => 'São Tomé and Príncipe Dobra', 'flag' => '🇸🇹', 'flag_url' => 'https://flagcdn.com/st.svg'],
            'SYP' => ['description' => 'Syrian Pound', 'flag' => '🇸🇾', 'flag_url' => 'https://flagcdn.com/sy.svg'],
            'SZL' => ['description' => 'Swazi Lilangeni', 'flag' => '🇸🇿', 'flag_url' => 'https://flagcdn.com/sz.svg'],
            'THB' => ['description' => 'Thai Baht', 'flag' => '🇹🇭', 'flag_url' => 'https://flagcdn.com/th.svg'],
            'TJS' => ['description' => 'Tajikistani Somoni', 'flag' => '🇹🇯', 'flag_url' => 'https://flagcdn.com/tj.svg'],
            'TMT' => ['description' => 'Turkmenistan Manat', 'flag' => '🇹🇲', 'flag_url' => 'https://flagcdn.com/tm.svg'],
            'TND' => ['description' => 'Tunisian Dinar', 'flag' => '🇹🇳', 'flag_url' => 'https://flagcdn.com/tn.svg'],
            'TOP' => ['description' => 'Tongan Paʻanga', 'flag' => '🇹🇴', 'flag_url' => 'https://flagcdn.com/to.svg'],
            'TRY' => ['description' => 'Turkish Lira', 'flag' => '🇹🇷', 'flag_url' => 'https://flagcdn.com/tr.svg'],
            'TTD' => ['description' => 'Trinidad and Tobago Dollar', 'flag' => '🇹🇹', 'flag_url' => 'https://flagcdn.com/tt.svg'],
            'TWD' => ['description' => 'New Taiwan Dollar', 'flag' => '🇹🇼', 'flag_url' => 'https://flagcdn.com/tw.svg'],
            'TZS' => ['description' => 'Tanzanian Shilling', 'flag' => '🇹🇿', 'flag_url' => 'https://flagcdn.com/tz.svg'],
            'UAH' => ['description' => 'Ukrainian Hryvnia', 'flag' => '🇺🇦', 'flag_url' => 'https://flagcdn.com/ua.svg'],
            'UGX' => ['description' => 'Ugandan Shilling', 'flag' => '🇺🇬', 'flag_url' => 'https://flagcdn.com/ug.svg'],
            'USD' => ['description' => 'United States Dollar', 'flag' => '🇺🇸', 'flag_url' => 'https://flagcdn.com/us.svg'],
            'UYU' => ['description' => 'Uruguayan Peso', 'flag' => '🇺🇾', 'flag_url' => 'https://flagcdn.com/uy.svg'],
            'UZS' => ['description' => 'Uzbekistani Som', 'flag' => '🇺🇿', 'flag_url' => 'https://flagcdn.com/uz.svg'],
            'VES' => ['description' => 'Venezuelan Bolívar', 'flag' => '🇻🇪', 'flag_url' => 'https://flagcdn.com/ve.svg'],
            'VND' => ['description' => 'Vietnamese đồng', 'flag' => '🇻🇳', 'flag_url' => 'https://flagcdn.com/vn.svg'],
            'VUV' => ['description' => 'Vanuatu Vatu', 'flag' => '🇻🇺', 'flag_url' => 'https://flagcdn.com/vu.svg'],
            'WST' => ['description' => 'Samoan Tala', 'flag' => '🇼🇸', 'flag_url' => 'https://flagcdn.com/ws.svg'],
            'XAF' => ['description' => 'Central African CFA Franc', 'flag' => '🇨🇫', 'flag_url' => 'https://flagcdn.com/cf.svg'],
            'XCD' => ['description' => 'East Caribbean Dollar', 'flag' => '🇰🇳', 'flag_url' => 'https://flagcdn.com/kn.svg'],
            'XOF' => ['description' => 'West African CFA franc', 'flag' => '🇼🇸', 'flag_url' => 'https://flagcdn.com/ws.svg'],
            'YER' => ['description' => 'Yemeni Rial', 'flag' => '🇾🇪', 'flag_url' => 'https://flagcdn.com/ye.svg'],
            'ZAR' => ['description' => 'South African Rand', 'flag' => '🇿🇦', 'flag_url' => 'https://flagcdn.com/za.svg'],
            'ZMW' => ['description' => 'Zambian Kwacha', 'flag' => '🇿🇲', 'flag_url' => 'https://flagcdn.com/zm.svg'],
        ];



        $currencyToCountry = [
            'AED' => 'AE',
            'AFN' => 'AF',
            'ALL' => 'AL',
            'AMD' => 'AM',
            'ANG' => 'BQ',
            'AOA' => 'AO',
            'ARS' => 'AR',
            'AUD' => 'AU',
            'AWG' => 'AW',
            'AZN' => 'AZ',
            'BAM' => 'BA',
            'BBD' => 'BB',
            'BDT' => 'BD',
            'BGN' => 'BG',
            'BHD' => 'BH',
            'BIF' => 'BI',
            'BMD' => 'BM',
            'BND' => 'BN',
            'BOB' => 'BO',
            'BRL' => 'BR',
            'BSD' => 'BS',
            'BTC' => '₿',
            'BTN' => 'BT',
            'BWP' => 'BW',
            'BYN' => 'BY',
            'BZD' => 'BZ',
            'CAD' => 'CA',
            'CDF' => 'CD',
            'CHF' => 'CH',
            'CLP' => 'CL',
            'CNY' => 'CN',
            'COP' => 'CO',
            'CRC' => 'CR',
            'CUC' => 'CU',
            'CUP' => 'CU',
            'CVE' => 'CV',
            'CZK' => 'CZ',
            'DJF' => 'DJ',
            'DKK' => 'DK',
            'DOP' => 'DO',
            'DZD' => 'DZ',
            'EGP' => 'EG',
            'ERN' => 'ER',
            'ETB' => 'ET',
            'EUR' => 'EU',
            'FJD' => 'FJ',
            'FKP' => 'FK',
            'GBP' => 'GB',
            'GEL' => 'GE',
            'GHS' => 'GH',
            'GIP' => 'GI',
            'GMD' => 'GM',
            'GNF' => 'GN',
            'GTQ' => 'GT',
            'GYD' => 'GY',
            'HKD' => 'HK',
            'HNL' => 'HN',
            'HRK' => 'HR',
            'HTG' => 'HT',
            'HUF' => 'HU',
            'IDR' => 'ID',
            'ILS' => 'IL',
            'INR' => 'IN',
            'IQD' => 'IQ',
            'IRR' => 'IR',
            'ISK' => 'IS',
            'JMD' => 'JM',
            'JOD' => 'JO',
            'JPY' => 'JP',
            'KES' => 'KE',
            'KGS' => 'KG',
            'KHR' => 'KH',
            'KMF' => 'KM',
            'KPW' => 'KP',
            'KRW' => 'KR',
            'KWD' => 'KW',
            'KYD' => 'KY',
            'KZT' => 'KZ',
            'LAK' => 'LA',
            'LBP' => 'LB',
            'LKR' => 'LK',
            'LRD' => 'LR',
            'LSL' => 'LS',
            'LYD' => 'LY',
            'MAD' => 'MA',
            'MDL' => 'MD',
            'MGA' => 'MG',
            'MKD' => 'MK',
            'MMK' => 'MM',
            'MNT' => 'MN',
            'MOP' => 'MO',
            'MRU' => 'MR',
            'MUR' => 'MU',
            'MVR' => 'MV',
            'MWK' => 'MW',
            'MXN' => 'MX',
            'MYR' => 'MY',
            'MZN' => 'MZ',
            'NAD' => 'NA',
            'NGN' => 'NG',
            'NIO' => 'NI',
            'NOK' => 'NO',
            'NPR' => 'NP',
            'NZD' => 'NZ',
            'OMR' => 'OM',
            'PAB' => 'PA',
            'PEN' => 'PE',
            'PGK' => 'PG',
            'PHP' => 'PH',
            'PKR' => 'PK',
            'PLN' => 'PL',
            'PYG' => 'PY',
            'QAR' => 'QA',
            'RON' => 'RO',
            'RSD' => 'RS',
            'RUB' => 'RU',
            'SAR' => 'SA',
            'SBD' => 'SB',
            'SCR' => 'SC',
            'SDG' => 'SD',
            'SEK' => 'SE',
            'SGD' => 'SG',
            'SHP' => 'SH',
            'SLL' => 'SL',
            'SOS' => 'SO',
            'SRD' => 'SR',
            'STN' => 'ST',
            'SYP' => 'SY',
            'SZL' => 'SZ',
            'THB' => 'TH',
            'TJS' => 'TJ',
            'TMT' => 'TM',
            'TND' => 'TN',
            'TOP' => 'TO',
            'TRY' => 'TR',
            'TTD' => 'TT',
            'TWD' => 'TW',
            'TZS' => 'TZ',
            'UAH' => 'UA',
            'UGX' => 'UG',
            'USD' => 'US',
            'UYU' => 'UY',
            'UZS' => 'UZ',
            'VES' => 'VE',
            'VND' => 'VN',
            'VUV' => 'VU',
            'WST' => 'WS',
            'XAF' => 'CF',
            'XCD' => 'KN',
            'XOF' => 'WS',
            'YER' => 'YE',
            'ZAR' => 'ZA',
            'ZMW' => 'ZM',
        ];


        if ($apiKey && $request->query->has('amount') && isset($symbols[$from]) && isset($symbols[$to])) {
            try {
                $response = $client->request('GET', 'https://api.exchangerate.host/convert', [
                    'query' => [
                        'access_key' => $apiKey,
                        'from' => $from,
                        'to' => $to,
                        'amount' => $amount,
                    ],
                ]);

                $data = $response->toArray();

                if (!empty($data['result']) && !empty($data['info']['quote'])) {
                    $result = $data['result'];
                    $rate = $data['info']['quote'];
                } else {
                    $this->addFlash('warning', 'Taux introuvable pour cette conversion.');
                }
            } catch (\Exception $e) {
                $this->addFlash('danger', 'Erreur API : ' . $e->getMessage());
            }
        } elseif (!$apiKey) {
            $this->addFlash('danger', 'Clé API manquante. Vérifie ton .env.local');
        }



        return $this->render('currency/index.html.twig', [
            'amount' => $amount,
            'from' => $from,
            'to' => $to,
            'rate' => $rate,
            'symbols' => $symbols,
            'result' => $result,
            'request' => $request,
            'currencyToCountry' => $currencyToCountry,
        ]);

    }
}
