parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Twig\AppExtension:
        tags: [ 'twig.extension' ]

    App\:
        resource: '../src/'

    App\Service\CurrencyService:
        arguments:
            $cache: '@cache.app'
